### ISSUE TITLE
Packaging, Distribution and Deployment for Open Source Release

### ISSUE THREAD

**Issue by chrisdail** [pravega/pravega#1087]
Issue to track the work required for PDP-15 (Proposal on packaging, distribution and deployment).

This set of improvements is about frictionless onboarding of new users by making our packaging, distribution and deployment options. The goals is to produce the best options possible for the Open Source release of Pravega (May 10).

**Packaging**

Packaging is the build work related to creating a distributable package for pravega. Most of this is build work in the gradle script for pravega. This package forms the basis of all other distributions (it is used in the docker, mesos and other distributions).

- [x] Manual Installation (Single and MultiNode) (#687)
  - [x] Build changes to create single/multi-node distributable package
  - [x] Build restructuring to new packaging
- [x] Create a release package for the clients (suitable to adding to github)
- [x] Create a release package for the javadocs (single zip)
- [x] Include docker container build as part of the overall build

**Distribution**

Distribution is all about how to provide release artifacts to users in places they would expect them. There are a few key places that we want to store different artifacts.

- [x] Maven Central - Support distributing jar files to io.pravega in maven central. (#1099)
- [x] Docker Hub - Support publishing docker images to docker hub (#1100)

**Deployment**

- [x] Standalone (from source via gradle, covered by packaging task)
- [x] Standalone or Multi-node via the binary package (described above in the packaging)
- [x] Docker Based Installation (#688)
  - [x] Docker-Compose (Local, distributed/multi-container)
  - [x] Docker Swarm (multiple nodes)
- [x] DC/OS Framework based on dcos-commons (#1101)
- [x] Public Cloud Distribution (AWS) (#1102)

**OnBoarding**

- [x] Update README - reflect how to build, run, test etc
- [x] Collect/combine deployment documentation
- [x] Document artifacts required for a "release" on github (including client)
- [x] Document dependencies (ZK version, Bookkeeper, HDFS version etc)
- [x] Update pravega-samples to work with a release (maven etc)
