### ISSUE TITLE
Lock-free transaction management in controller

### ISSUE THREAD

**Issue by bhargav-gulavani** [pravega/pravega#1151]
**Problem description**
Currently, following are the locks used in transaction operations in controller
1. Create transaction locks the stream resource.
2. Commit/Abort transaction locks transaction resource
These locks are redundant, if we carefully avoid conflicts with stream scale operation.

**Problem location**
Controller transaction management

**Suggestions for an improvement**
Carefully resolve conflicts between transaction creation and scale operation so that no locking is required for transaction management

- [x] Update stream transaction metadata store to support epochs #1277 
- [ ] Update stream scale operation to support rolling transactions #179
- [x] Move transaction management operations out of task framework #1222 
- [x] Create transaction index that maps controller process to the transactions it manages timeouts for #1278

**Comment by bhargav-gulavani** [comment]
Fixed in #1334
