### ISSUE TITLE
REST interface to Pravega control plane

### ISSUE THREAD

**Issue by ramviswanathan** [pravega/pravega#117]
There are some scenarios where it makes sense to implement a REST interface to Pravega control plane.  This will replace the current Pravega control API.

Subtasks:
- [x] Designing REST API
- [x] Implement REST Skeleton- PR https://github.com/emccode/pravega/pull/330
- [x] Implement  (SET-1) CreateStream, UpdateStream, GetStreamConfig API calls  SET-1, Issue #423 ,  PR: https://github.com/emccode/pravega/pull/388
- [x] Implement create and delete scope internal calls of controller - Issue: https://github.com/emccode/pravega/issues/348
- [x] Implement (SET-2) CreateScope, DeleteScope, ListScopes, ListStreamsInScope REST API calls
- [x] Add Swagger integration code - Issue: https://github.com/emccode/pravega/issues/380
