### ISSUE TITLE
Consume events as a group

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#128]
On event consumption end, multiple consumers can act as a group to consume from one or more streams. An event will be delivered to only one member of a consumer group. Stream segments should be allocated equally among members of a consumer group to achieve parallelism.

- [x] Create synchronizer to coordinate within a ReaderGroup #381 
- [x] Consumer groups wrapping low level consumer api #180 
- [x] Low level consumer; pause stream on end of segment #176
- [x] Rebalance heuristic for consumer groups #195 
- [x] Controller support for tracking successors and predecessors #382
- [x] Readers use ReaderGroupState #383
- [ ] Consumer group revisioning #371 
- [x] Checkpoint and restore #474
