### ISSUE TITLE
Lock-free transaction management

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1389]
**Problem description**
Controller exposes the following operations for transaction management,

- Create Transaction (`CreateTxn`)
- Abort Transaction (`AbortTxn`)
- Commit Transaction (`CommitTxn`)

In the current design, we lock a stream resource before initiating CreateTxn and Scale tasks to avoid mutual interference, and we lock the transaction resource again before AbortTxn and CommitTxn tasks to avoid interference. The problem we want to solve here is to perform the above transaction management tasks without locking the resource we are currently locking. 

**Problem location**
Controller, txns, scaling.

**Suggestions for an improvement**
Implementing this issue comprises three tasks:

- [ ]  Enable stream epochs (Issue #1277)
- [ ]  Lock-free scaling (Issue #1392 )
- [ ]  Lock-free txns (Issue #1222)
