### ISSUE TITLE
Pravega Security: Authentication, Authorization, Channel encryption

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1669]
**Problem description**
Security is critical to many environments where Pravega runs. This issue is to track the development of Pravega security, specifically authentication, authorization, and channel encryption.

Here is a PDP associated with this:
https://github.com/pravega/pravega/wiki/PDP-23:-Pravega-security----encryption-and-Role-Based-Access-Control

Here is an issue for discussions for the PDP.
https://github.com/pravega/pravega/issues/1950

This issue is divided into following subitems:
1. Configuration changes:
- [x] Control different aspects of security through Pravega configurations (issue #2090 )
2. Encryption
   

- [ ] Design a cert generation/distribution during deployment mechanism
-  [x] Implement secure TLS channels between client and controller/segmentstore - issue #2147 
- [x] Implement secure TLS server for REST API - issue #2578
-  [x] Configure and use secure TLS channels between sever components and ZK, components and BK, between BK and ZK.
- [ ] Enable storing encrypted data on disk for BK and tier-2.

2. RBAC:
- [x] Implement sample authentication on gRPC controller side - issue #2091.
- [x] Implement sample authentication on the client - issue #2101.
- [x] Implement sample authorization on gRPC controller side - issue #2117.
- [x] Implement pluggable mechanism on the client and controller - issue #2125.
- [x] Implement JWT token creation and management on controller side - issue #2147.
- [x] Implement Token decipher and apply constraints on segmentstore - issue #2147
- [x] Implement token refresh mechanism between controller and client - issue #2147, issue #2330 
- [ ] Implement creation and distribution of async keys (certs) to different components during deployment
- [x] Implement a default authorization DB for sample auth on controller. - issue #2147 
- [ ] Implement mechanism using which auth for tier-2 and BK can be passed to segme
nt store securely (through vault?)

3. Documentation
- [x] Update Pravega website with security documentation - issue #2591
- [ ] Update threat modelling documentation - issue #2590
- [ ] Document the plugin runtime environment - issue #2404 

**Problem location**
Security.

**Suggestions for an improvement**
Design and implement.

**Comment by fpj** [comment]
Supersedes #173 #109

**Comment by fpj** [comment]
@arvindkandhare 
> Do we need it on REST?

Yes, all accesses to the controller need to be secured.
