### ISSUE TITLE
Segment Store: ReadIndex improvements

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#212]
There are a number of improvements that can be made to the ReadIndex to reduce its memory usage significantly. These are tracked in the following subtasks:
- [x] #379: Route all Cache access through the ReadIndex
- [x] #393: Index all ReadIndex entries by StartOffset
- [ ] #394: Coalesce small appends into bigger index entries
- [x] #395: Replace TreeMap with AVLTree
