### ISSUE TITLE
Enable getStreamInfo api in BatchClient.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#2453]
**Problem description**

Enable `getStreamInfo` api in the batch client with retrieves information about the stream.
The attributes include.
-  Stream name.
-  Stream scope.
-  StreamCut pointing to the current HEAD of the stream.
-  StreamCut pointing to the current TAIL of the stream.
-  Stream Seal Status.
-  Stream Creation time.
- Stream end Time (! to be reviewed.)

**Problem location**
BatchClient.

**Suggestions for an improvement**
Implement the API.

**Comment by shrids** [comment]
- [ ] Stream name (ref: #2454)
- [ ] Stream scope.(ref: #2454)
- [ ] StreamCut pointing to the current HEAD of the stream. (#2454)
- [ ] StreamCut pointing to the current TAIL of the stream. (#2454)
- [ ] Stream Seal Status.
- [ ] Stream Creation time.
- [ ] Stream end Time (! to be reviewed.)

**Comment by shrids** [comment]
Closing this as getStreamInfo api has been deprecated for BatchClient.
