### ISSUE TITLE
Migrate Pravega metrics into Micrometer based to support dimensional metric data model

### ISSUE THREAD

**Issue by kevinhan88** [pravega/pravega#3319]
**Problem description**
Pravega application metrics needs to support dimensional data model for metrics back end to take full advantage of rich queries crossing dimensions and measurements.
With the support of dimensional data model, Pravega will be able to talk to time series database directly without local agent such as Telegraf.

**Problem location**
Replace the existing readytalk statsD and codahale libraries, and the application codes based on them.
Replace all the application codes calling method to flat metric name with dimensions, to use the new API with tag support.

**Suggestions for an improvement**
Replace existing readytalk and codahale with Micrometer to support dimensional data model;

This umbrella issue covers issues:

- [ ] Update statsd library to send the correct metric type (#3004) 
- [ ] Use Micrometer library for Pravega metrics(#2977) 
- [ ] Enable Configurable Stats Providers in Bookkeper docker container (#3101) 
- [ ] #3405 Add tags to those metrics defined by the Platform team

**Comment by ravisharda** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [3277 - Revisit authorization logic](https://trello.com/c/TbQ1aPTA/1-3277-revisit-authorization-logic)

**Comment by kevinhan88** [comment]
The feedback received from the Platform team:
1. The Prometheus is not an immediate option for Pravega as of now, particularly considering an embedded HTTP endpoint is needed if Prometheus is used.
2. After the refactoring, Platform team will skip Telegraf agent and let Pravega talk to InfluxDB directly.
3. Telegraf mapping file is provided.
4. The refactoring will be done in two steps: the first step is to replace the underlying metric libraries with Micrometer; the second step is to add tags into those metrics on the mapping file and test the direct InfluxDB option.
