### ISSUE TITLE
Implement a framework for system tests

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#376]
**Problem description**
We have a preliminary design of a test framework reported in the PDP-03 doc. We need now to implement it.

**Problem location**
This framework targets improving our ability to implement and run system tests. 

Subtasks:
- [x] Gradle task for system tests. Issue: https://github.com/emccode/pravega/issues/432
- [x] Java based Custom Junit runner for executing SystemTests. Issue: #433
- [x] system test jar should be passed to docker container.Issue: #434 
- [x] Automate creation of Jarvis virtual clusters via command line #473 
- [x] Simple test case #605
