### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#404]
We will soon be releasing and we need a plan of how to prepare the release process. Preparing for a release has a few important high-level steps:

- Agree with the team a code freeze day so that we can generate the artifacts
- Prepare the artifacts and stage them
- Test the staged artifacts
- Publish the artifacts

To get there, we need to execute a few sub-tasks:
- [x] Define the artifacts we will be generating (e.g., docker images, RPM/Debian packages, maven) #405 
- [x] Detail the release process plan (e.g., how to produce a release candidate, create a tag, sign, etc.) #406 
- [x] Create a checklist for testing the artifacts so that engineers across the team can execute it #407
