### ISSUE TITLE
Key Value Tables

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4569]
**Problem description**
Parent ticket for the following issues:

- [x]  #4568: Key Value Table API
- [x]  #4603: Client-side Controller API contracts.
- [x]  #4571: Control Path Implementation
- [x]  #4333: Client-Side TableSegment API
- [x]  #4656: Segment Iterator Filters
- [x]  #4570: Data Path Implementation
- [x] #4771: Data Path - Java Map Abstraction
- [x]  #3637: Enable TableSegment Compaction
- [x]  #4796: Create Key-Value Table (Controller)
- [ ]  #4879: List & Delete Key-Value Table (Controller)

See [PDP-39](https://github.com/pravega/pravega/wiki/PDP-39-Key-Value-Tables) for details.

**Problem location**
Client, Controller and Segment Store.

**Suggestions for an improvement**
Implement all

**Comment by eolivelli** [comment]
@andreipaduroiu 
I find this work very interesting.

It overlaps with the StreamStorage service built-in in BookKeeper. Basically the features are the same.

Do you have time to take a look ?
Unfortunately there is no documentation.
It is actually the basic storage for state in Pulsar Functions (but I am not an user of it, so I can't tell more)

You can find it in "stream" module of BookKeeper Codebase 

cc @fpj

**Comment by andreipaduroiu** [comment]
I know that since 4.8.x, Bookkeeper has a Table Service, which looks like it was contributed by the Pulsar community - is this what you are referring to? I read through the BP associated with it and I found that very interesting.

However the work that we are doing here is a bit different. We already have the basic building blocks (`TableSegment` - a non-distributed KV store backed by a single Pravega Segment) and the goal of this PDP is to turn that into a Distributed KV Store by placing them into partitions (more advanced work can follow later but this is a good step to get it out there).

We use Table Segments extensively internally. Our Controller stores almost all of its metadata in them and the Segment Store stores Segment Metadata and Tier 2 Metadata in these segments. They allow atomic, conditional/unconditional updates and removes (one or more keys at a time), key retrievals and iterators. Each update is essentially a BK write, the index is stored in Segment Attributes (Tier 2 append-only B+Tree with 2 layers of caching above it) and reads will either go to Tier 2 (for cold keys) or read directly from memory (for frequently used keys).

It was only natural to expand this to a `KeyValueTable` which is the distributed version of it. We have heard some people in the community express interest in it and the work to get a "basic" 
KV store out is not that much, given that we already have the Table Segments.

One of my main goals with this PDP is to define the external API as well as possible. I don't think we'll get it 100% right from the first attempt, but it we get the contracts and (external) behavior well established then we can continue working internally to improve it later.

**Comment by eolivelli** [comment]
@andreipaduroiu 
I see value in this work and I have followed most of the works you did and cited above.

Thanks for your answer
