### ISSUE TITLE
Pravega Consumption Based Retention

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#5108]
**Problem description**

PDP : https://github.com/pravega/pravega/wiki/PDP-47-(Pravega-Streams-Consumption-Based-Retention)

Parent ticket for the following issues:
- [x]  #5109: Add/Remove Subscriber Controller API
- [x]  #5110: Update Truncation Stream-Cut Controller API
- [x]  #5111: Truncate a Stream with CBR Policy - Controller 
- [x]  #5112: Client API to Create Subscriber reader groups
- [x]  #5114: Client API to UpdateTruncationStreamCut to Controller
- [x]  #5203 : Stream-Cuts get saved as "Checkpoints" in RGState.
- [x]  #5324 : addSubscriber and deleteSubscriber APIs on Controller should support generations
- [ ]  #5350 : User documentation for Consumption based retention.
- [x]  #5356 : Make CBR an implicit retention type for a Stream based on Reader Groups publishing Stream-Cuts.
- [x]  #5384 : Add Create, Update and Remove Reader Group APIs on Controller.
- [ ]  #5553:  System Tests for validating CBR functionality.

**Problem location**
Client, Controller, System Test Framework, Documentation

**Suggestions for an improvement**
Implement and fix all

**Comment by RaulGracia** [comment]
@pbelgundi @shshashwat @bhargav-gulavani is this issue actually resolved? I remember that we have one system tests about consumption based retention, and I don't really know the state of documentation for this. It would be great to wrap up this one, as it has been there for some time and the feature is actually developed.

**Comment by shshashwat** [comment]
All sub-issues fixed and merged with master
