### ISSUE TITLE
Add System Tests for Consumption Based Retention of data on Streams

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#5553]
**Problem description**
This issue tracks addition of System tests for the feature Consumption Based Retention of data on Streams.

Parent ticket for the following issues:
- [ ]  #5554 : Test Consumption Based Retention with Single Subscriber and multiple non-subscribers.
- [ ]  #5555 : Test Consumption Based Retention with Multiple Controllers.
- [ ]  #5556 : Test Consumption Based Retention with Controller and Segment Store restarts (failover).
- [ ]  #5557 : Test Consumption Based Retention with Stream Scaling.
- [ ]  #5558 : Test Retention policy change at runtime.
- [ ]  #5559 : Test Consumption based Retention with multiple Subscriber and Non-Subscriber Reader Groups.

**Problem location**
System Tests

**Suggestions for an improvement**
1. List out system tests to be added.
2. Add new tests to System test framework.

**Comment by RaulGracia** [comment]
@shshashwat can we please wrap up this one so we can complete the consumption-based retention story?

**Comment by ShwethaSNayak** [comment]
Added new system tests for all CBR scenario so closing
