### ISSUE TITLE
Enable Stream Tags on Pravega.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#6013]
Master issue for StreamTag work tracking.
- PDP: [PDP-50](https://github.com/pravega/pravega/wiki/PDP-50:-Stream-Tags)

Tasks:
- [x] #6009 Enable Controller GRPC server APIs for StreamTags.
- [x] #6010 Pravega Java Client related changes.
- [x] #6011 Enable Stream Tag APIs on the Controller REST endpoint.
- [x] https://github.com/pravega/pravega-client-rust/issues/256 RUST client changes for Tag APIs.
- [x] #6012 Create System tests.
- [x] #6147 Update Documentation.

(add tasks above as they are created)
