### ISSUE TITLE
Large Events Tracker issue

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#6107]
Tracker issue for all work related to implementing Large Events. See [PDP-43A](https://github.com/pravega/pravega/wiki/PDP-43A-Large-Events-(Simplified)).

- [ ] Create feature branch `feature-large-events`.
- [ ] Setup Wire Commands
- [ ] TBD: add tasks for segment store here
- [ ] TBD: add tasks for client here.
- [ ] Merge feature branch into master.
