### ISSUE TITLE
Transaction Performance Improvements

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#6243]
**Is your feature request related to a problem? Please describe.**
Currently Transactions on Pravega Streams are bottlenecked by multiple inefficiencies which impact their performance and scalability.

**Describe the solution you'd like**
The following areas have been identified as performance bottlenecks, which need to be worked upon to improve transactional performance:
1. Transaction Commit Processing time.
2. Transaction Create Processing time.
3. Transaction timeout management.
4. Metric computation inefficiencies.
5. Number of segments activated by Transactions during commit processing.

**Describe alternatives you've considered**
It has been observed that the following solution help improve transactions commit processing time:
- [x]  #6061 Simplify processing for recording commit offsets, post transaction segment merge.
- [x]  #5640: Optimize open transaction metric count computation.
- [ ]  #6110: Commit Event processing should pipeline and batch merge transactional segments.
- [ ] # 6241: Simplify transaction timeout management.
- [ ] # 6242: Lazy creation of transactional segments.
