### ISSUE TITLE
Frictionless Onboarding

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#782]
New users are spending too much time on installing, configuring, and familiarizing themselves with Pravega . We need to make the initial on-boarding experience as smooth as possible. For that reason, I will keep track of sub issue as a feature here.

- [x]  Straightforward install experience ( #1087 )
- [ ]  Set of cli admin tools to manage and monitor cluster/streams ( #703 )
- [x]  Set of cli tools to read/write stream ( #702 )
- [x]  Sample codes for each feature under https://github.com/pravega/pravega-samples ( #153 )
- [x]  User documentation ( #359 )
