### ISSUE TITLE
Transaction Support

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#83]
Producers should be able to ingest series of events as a transaction, ensuring that all messages are delivered exactly once. 

Remaining tasks:
- [x] Design in #193  and #192 
- [x] Implement txn commits #102, #182
- [x] Implement txn timeouts PR #580
